language: php

dist: trusty

php:
  - '7.2'
  - '7.3'

install: 
  - composer install
  - composer require --dev php-coveralls/php-coveralls

script: 
  - mkdir -p build/logs
  - phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
